//
//  DataProvider.m
//  Groceries
//
//  Created by Jon Pedersen on 15/02/11.
//  Copyright 2011 jApps. All rights reserved.
//

#import "DataProvider.h"
#import "RootViewController.h"


@implementation DataProvider
static int const DEFAULT_HOURS_SINCE_LAST_CHECK = 24;

@synthesize controller;

- (void)addDefaultData {
	NSLocale *locale = [NSLocale currentLocale];
	if ([@"da_DK" isEqualToString:[locale localeIdentifier]]) {
		[controller insertNewObject:@"Brød" defaultEventsWithHours:48 sortBy:@"Brød og morgenmad"];
		[controller insertNewObject:@"Rugbrød" sortBy:@"Brød og morgenmad"];
		[controller insertNewObject:@"Knækbrød" sortBy:@"Brød og morgenmad"];
		[controller insertNewObject:@"Kammerjunkere" defaultEventsWithHours:48 sortBy:@"Brød og morgenmad"];
		[controller insertNewObject:@"Havregryn" sortBy:@"Brød og morgenmad"];
		[controller insertNewObject:@"Mysli" sortBy:@"Brød og morgenmad"];
		[controller insertNewObject:@"Panodil" sortBy:@"Diverse"];
		[controller insertNewObject:@"Avis" sortBy:@"Diverse"];
		[controller insertNewObject:@"Isthe" sortBy:@"Drikkevarer"];
		[controller insertNewObject:@"Juice" sortBy:@"Drikkevarer"];
		[controller insertNewObject:@"Kaffe" sortBy:@"Drikkevarer"];
		[controller insertNewObject:@"Kildevand" sortBy:@"Drikkevarer"];
		[controller insertNewObject:@"Saftevand" sortBy:@"Drikkevarer"];
		[controller insertNewObject:@"Sodavand" sortBy:@"Drikkevarer"];
		[controller insertNewObject:@"The" sortBy:@"Drikkevarer"];
		[controller insertNewObject:@"Boller, frosne" sortBy:@"Frostvarer"];
		[controller insertNewObject:@"Grøntsager, frosne" sortBy:@"Frostvarer"];
		[controller insertNewObject:@"Bær, frosne" sortBy:@"Frostvarer"];
		[controller insertNewObject:@"Færdigret, frossen" sortBy:@"Frostvarer"];
		[controller insertNewObject:@"Fjerkræ, frossen" sortBy:@"Frostvarer"];
		[controller insertNewObject:@"Fisk, frossen" sortBy:@"Frostvarer"];
		[controller insertNewObject:@"Skaldyr, frosne" sortBy:@"Frostvarer"];
		[controller insertNewObject:@"Is" sortBy:@"Frostvarer"];
		[controller insertNewObject:@"Ananas" sortBy:@"Frugt"];
		[controller insertNewObject:@"Appelsiner" sortBy:@"Frugt"];
		[controller insertNewObject:@"Bananer" sortBy:@"Frugt"];
		[controller insertNewObject:@"Blommer" sortBy:@"Frugt"];
		[controller insertNewObject:@"Bær" sortBy:@"Frugt"];
		[controller insertNewObject:@"Citroner" sortBy:@"Frugt"];
		[controller insertNewObject:@"Clementiner" sortBy:@"Frugt"];
		[controller insertNewObject:@"Grapefrugt" sortBy:@"Frugt"];
		[controller insertNewObject:@"Kiwi" sortBy:@"Frugt"];
		[controller insertNewObject:@"Lime" sortBy:@"Frugt"];
		[controller insertNewObject:@"Mango" sortBy:@"Frugt"];
		[controller insertNewObject:@"Melon" sortBy:@"Frugt"];
		[controller insertNewObject:@"Pærer" sortBy:@"Frugt"];
		[controller insertNewObject:@"Vindruer" sortBy:@"Frugt"];
		[controller insertNewObject:@"Æbler" sortBy:@"Frugt"];
		[controller insertNewObject:@"Agurk" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Avocado" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Broccoli" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Bønnespirer" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Champignon" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Courgette" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Gulerødder" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Kartofler" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Krydderurt" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Majs, hele" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Peberfrugt" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Porrer" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Radiser" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Salat" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Spinat" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Tomater" sortBy:@"Grøntsager"];
		[controller insertNewObject:@"Affaldsposer" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Bagepapir" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Batterier" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Elpærer" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Folie" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Fryseposer" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Husholdningsfilm" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Karklude" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Køkkenrulle" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Madpapir" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Opvaskemiddel" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Rengøringsmiddel" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Toiletpapir" sortBy:@"Husholdningsartikler"];
		[controller insertNewObject:@"Bagepulver" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Brødblanding" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Durum mel" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Flormelis" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Frø" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Fuldkornsmel" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Hjortetaksalt" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Hvedemel" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Kageblanding" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Kartoffelmel" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Kerner" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Mandler" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Natron" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Nødder" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Rasp" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Rugmel" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Sigtemel" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Sirup" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Speltmel" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Sukker" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Vanilie" sortBy:@"Ingredienser"];
		[controller insertNewObject:@"Agurkesalat" sortBy:@"Konserves"];
		[controller insertNewObject:@"Asier" sortBy:@"Konserves"];
		[controller insertNewObject:@"Baked beans" sortBy:@"Konserves"];
		[controller insertNewObject:@"Flåede tomater" sortBy:@"Konserves"];
		[controller insertNewObject:@"Kapers" sortBy:@"Konserves"];
		[controller insertNewObject:@"Kokosmælk" sortBy:@"Konserves"];
		[controller insertNewObject:@"Majs, dåse" sortBy:@"Konserves"];
		[controller insertNewObject:@"Makrel i tomat" sortBy:@"Konserves"];
		[controller insertNewObject:@"Mangochutney" sortBy:@"Konserves"];
		[controller insertNewObject:@"Muslinger" sortBy:@"Konserves"];
		[controller insertNewObject:@"Oliven" sortBy:@"Konserves"];
		[controller insertNewObject:@"Pesto" sortBy:@"Konserves"];
		[controller insertNewObject:@"Rødkål" sortBy:@"Konserves"];
		[controller insertNewObject:@"Sardiner" sortBy:@"Konserves"];
		[controller insertNewObject:@"Tun i vand" sortBy:@"Konserves"];
		[controller insertNewObject:@"Allehånde" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Balsamico" defaultEventsWithHours:192 sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Basilikum" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Boullion" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Dressing" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Estragon" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Fond" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Gurkemeje" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Herbes de provence" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Ingefær" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Kardemomme" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Karry" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Ketchup" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Koriander" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Laurbærblade" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Mayonnaise" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Olivenolie" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Oregano" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Paprika" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Remoulade" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Rosmarin" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Safran" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Salt" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Salvie" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Sauce" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Sennep" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Sort peber" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Soya" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Suppe" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Timian" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Vindruekerneolie" sortBy:@"Krydderier & olie"];
		[controller insertNewObject:@"Fisk" sortBy:@"Kød & fisk"];
		[controller insertNewObject:@"Kalkun" sortBy:@"Kød & fisk"];
		[controller insertNewObject:@"Kalvekød" sortBy:@"Kød & fisk"];
		[controller insertNewObject:@"Kylling" sortBy:@"Kød & fisk"];
		[controller insertNewObject:@"Lammekød" sortBy:@"Kød & fisk"];
		[controller insertNewObject:@"Oksekød" defaultEventsWithHours:48 sortBy:@"Kød & fisk"];
		[controller insertNewObject:@"Svinekød" sortBy:@"Kød & fisk"];
		[controller insertNewObject:@"Vildt" sortBy:@"Kød & fisk"];
		[controller insertNewObject:@"Cacao" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Creme fraiche" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Fløde" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Gær" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Hytteret" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Margarine" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Mælk" defaultEventsWithHours:48 sortBy:@"Mejeri"];
		[controller insertNewObject:@"Ost" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Revet ost" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Risdrik" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Smoothie" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Smør" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Smøreost" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Sojadrik" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Ymer" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Yoghurt" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Æg" sortBy:@"Mejeri"];
		[controller insertNewObject:@"Balsam" sortBy:@"Personlig pleje"];
		[controller insertNewObject:@"Creme" sortBy:@"Personlig pleje"];
		[controller insertNewObject:@"Håndsæbe" sortBy:@"Personlig pleje"];
		[controller insertNewObject:@"Kosttilskud" sortBy:@"Personlig pleje"];
		[controller insertNewObject:@"Shampoo" sortBy:@"Personlig pleje"];
		[controller insertNewObject:@"Tandpasta" sortBy:@"Personlig pleje"];
		[controller insertNewObject:@"Chokoladecreme" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Frugtpålæg" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Honning" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Kødpålæg" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Marmelade" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Paté" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Postej" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Pålægschokolade" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Pølse" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Salat, pålæg" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Sild" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Syltetøj" sortBy:@"Pålæg"];
		[controller insertNewObject:@"Brune ris" sortBy:@"Ris & pasta"];
		[controller insertNewObject:@"Grødris" sortBy:@"Ris & pasta"];
		[controller insertNewObject:@"Lasagneplader" sortBy:@"Ris & pasta"];
		[controller insertNewObject:@"Pasta" sortBy:@"Ris & pasta"];
		[controller insertNewObject:@"Ris" sortBy:@"Ris & pasta"];
		[controller insertNewObject:@"Spaghetti" sortBy:@"Ris & pasta"];
		[controller insertNewObject:@"Chokolade" sortBy:@"Snacks & kager"];
		[controller insertNewObject:@"Kage" sortBy:@"Snacks & kager"];
		[controller insertNewObject:@"Kiks" sortBy:@"Snacks & kager"];
		[controller insertNewObject:@"Pastiller" sortBy:@"Snacks & kager"];
		[controller insertNewObject:@"Slik" sortBy:@"Snacks & kager"];
		[controller insertNewObject:@"Småkager" sortBy:@"Snacks & kager"];
		[controller insertNewObject:@"Snacks" sortBy:@"Snacks & kager"];
		[controller insertNewObject:@"Tyggegummi" sortBy:@"Snacks & kager"];
		[controller insertNewObject:@"Vafler" sortBy:@"Snacks & kager"];
		[controller insertNewObject:@"Cider" sortBy:@"Øl, vin & spiritus"];
		[controller insertNewObject:@"Hvidvin" sortBy:@"Øl, vin & spiritus"];
		[controller insertNewObject:@"Rødvin" sortBy:@"Øl, vin & spiritus"];
		[controller insertNewObject:@"Vodka" sortBy:@"Øl, vin & spiritus"];
		[controller insertNewObject:@"Whiskey" sortBy:@"Øl, vin & spiritus"];
		[controller insertNewObject:@"Øl" sortBy:@"Øl, vin & spiritus"];
	} else {
		[controller insertNewObject:@"Bagels" defaultEventsWithHours:24 sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Bread" sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Buns" sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Cake" sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Cookies" sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Doughnuts" sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Muffins" sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Pastries" sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Rolls" sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Tortillas" sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Wraps" sortBy:@"Bakery and Bread"];
		[controller insertNewObject:@"Apple Juice" sortBy:@"Beverages"];
		[controller insertNewObject:@"Cocoa" defaultEventsWithHours:36 sortBy:@"Beverages"];
		[controller insertNewObject:@"Coffee" sortBy:@"Beverages"];
		[controller insertNewObject:@"Lemonade" sortBy:@"Beverages"];
		[controller insertNewObject:@"Milk" sortBy:@"Beverages"];
		[controller insertNewObject:@"Orange Juice" sortBy:@"Beverages"];
		[controller insertNewObject:@"Soda Pop" sortBy:@"Beverages"];
		[controller insertNewObject:@"Sports Drinks" sortBy:@"Beverages"];
		[controller insertNewObject:@"Tea" sortBy:@"Beverages"];
		[controller insertNewObject:@"Water" sortBy:@"Beverages"];
		[controller insertNewObject:@"Bacon" sortBy:@"Breakfast"];
		[controller insertNewObject:@"Breakfast Bars" sortBy:@"Breakfast"];
		[controller insertNewObject:@"Cereal" sortBy:@"Breakfast"];
		[controller insertNewObject:@"Oatmeal" sortBy:@"Breakfast"];
		[controller insertNewObject:@"Pancakes" sortBy:@"Breakfast"];
		[controller insertNewObject:@"Sausages" sortBy:@"Breakfast"];
		[controller insertNewObject:@"Toaster Pastries" sortBy:@"Breakfast"];
		[controller insertNewObject:@"Baked Beans" sortBy:@"Canned Goods"];
		[controller insertNewObject:@"Canned Soup" sortBy:@"Canned Goods"];
		[controller insertNewObject:@"Canned Tomatoes" sortBy:@"Canned Goods"];
		[controller insertNewObject:@"Canned Tuna" sortBy:@"Canned Goods"];
		[controller insertNewObject:@"Chili" sortBy:@"Canned Goods"];
		[controller insertNewObject:@"Pasta" sortBy:@"Canned Goods"];
		[controller insertNewObject:@"Pasta Sauce" sortBy:@"Canned Goods"];
		[controller insertNewObject:@"Rice" defaultEventsWithHours:14 sortBy:@"Canned Goods"];
		[controller insertNewObject:@"Taco Mix" sortBy:@"Canned Goods"];
		[controller insertNewObject:@"Jam" sortBy:@"Condiments"];
		[controller insertNewObject:@"Jelly" sortBy:@"Condiments"];
		[controller insertNewObject:@"Ketchup" sortBy:@"Condiments"];
		[controller insertNewObject:@"Marinade" sortBy:@"Condiments"];
		[controller insertNewObject:@"Mayonnaise" sortBy:@"Condiments"];
		[controller insertNewObject:@"Mustard" sortBy:@"Condiments"];
		[controller insertNewObject:@"Olives" sortBy:@"Condiments"];
		[controller insertNewObject:@"Peanut Butter" sortBy:@"Condiments"];
		[controller insertNewObject:@"Pickles" defaultEventsWithHours:33 sortBy:@"Condiments"];
		[controller insertNewObject:@"Salad Dressing" sortBy:@"Condiments"];
		[controller insertNewObject:@"Vinegar" sortBy:@"Condiments"];
		[controller insertNewObject:@"Butter" sortBy:@"Dairy, Eggs & Cheese"];
		[controller insertNewObject:@"Cheese" sortBy:@"Dairy, Eggs & Cheese"];
		[controller insertNewObject:@"Eggs" sortBy:@"Dairy, Eggs & Cheese"];
		[controller insertNewObject:@"Margarine" sortBy:@"Dairy, Eggs & Cheese"];
		[controller insertNewObject:@"Yogurt" sortBy:@"Dairy, Eggs & Cheese"];
		[controller insertNewObject:@"Chicken Nuggets" sortBy:@"Frozen Foods"];
		[controller insertNewObject:@"Frozen Appetizers" sortBy:@"Frozen Foods"];
		[controller insertNewObject:@"Frozen Entrees" sortBy:@"Frozen Foods"];
		[controller insertNewObject:@"Frozen Pizza" sortBy:@"Frozen Foods"];
		[controller insertNewObject:@"Frozen Vegetables" sortBy:@"Frozen Foods"];
		[controller insertNewObject:@"Frozen Waffles & Pancakes" sortBy:@"Frozen Foods"];
		[controller insertNewObject:@"Ice Cream" sortBy:@"Frozen Foods"];
		[controller insertNewObject:@"Apples" sortBy:@"Fruits"];
		[controller insertNewObject:@"Bananas" sortBy:@"Fruits"];
		[controller insertNewObject:@"Grapefruit" sortBy:@"Fruits"];
		[controller insertNewObject:@"Grapes" sortBy:@"Fruits"];
		[controller insertNewObject:@"Lemons" defaultEventsWithHours:55 sortBy:@"Fruits"];
		[controller insertNewObject:@"Mangos" sortBy:@"Fruits"];
		[controller insertNewObject:@"Oranges" defaultEventsWithHours:48 sortBy:@"Fruits"];
		[controller insertNewObject:@"Peaches" sortBy:@"Fruits"];
		[controller insertNewObject:@"Pears" sortBy:@"Fruits"];
		[controller insertNewObject:@"Watermelon" defaultEventsWithHours:72 sortBy:@"Fruits"];
		[controller insertNewObject:@"Shampoo" sortBy:@"Health & Beauty"];
		[controller insertNewObject:@"Toothpaste" sortBy:@"Health & Beauty"];
		[controller insertNewObject:@"Vitamins" sortBy:@"Health & Beauty"];
		[controller insertNewObject:@"All-Purpose Cleaner" sortBy:@"Household Supplies"];
		[controller insertNewObject:@"Detergent" sortBy:@"Household Supplies"];
		[controller insertNewObject:@"Dish Soap" sortBy:@"Household Supplies"];
		[controller insertNewObject:@"Fabric Softener" sortBy:@"Household Supplies"];
		[controller insertNewObject:@"Napkins" sortBy:@"Household Supplies"];
		[controller insertNewObject:@"Paper Towels" sortBy:@"Household Supplies"];
		[controller insertNewObject:@"Toilet Tissue" sortBy:@"Household Supplies"];
		[controller insertNewObject:@"Cake Mix" sortBy:@"Ingredients"];
		[controller insertNewObject:@"Cornmeal" sortBy:@"Ingredients"];
		[controller insertNewObject:@"Flour" sortBy:@"Ingredients"];
		[controller insertNewObject:@"Honey" sortBy:@"Ingredients"];
		[controller insertNewObject:@"Olive Oil" sortBy:@"Ingredients"];
		[controller insertNewObject:@"Sugar" sortBy:@"Ingredients"];
		[controller insertNewObject:@"Syrup" sortBy:@"Ingredients"];
		[controller insertNewObject:@"Vegetable Oil" sortBy:@"Ingredients"];
		[controller insertNewObject:@"Ground Beef" sortBy:@"Meat, Seafood & Poultry"];
		[controller insertNewObject:@"Pork" sortBy:@"Meat, Seafood & Poultry"];
		[controller insertNewObject:@"Steak" sortBy:@"Meat, Seafood & Poultry"];
		[controller insertNewObject:@"Chicken" sortBy:@"Meat, Seafood & Poultry"];
		[controller insertNewObject:@"Hot Dogs" sortBy:@"Meat, Seafood & Poultry"];
		[controller insertNewObject:@"Shrimp" sortBy:@"Meat, Seafood & Poultry"];
		[controller insertNewObject:@"Fish" sortBy:@"Meat, Seafood & Poultry"];
		[controller insertNewObject:@"Shellfish" sortBy:@"Meat, Seafood & Poultry"];
		[controller insertNewObject:@"Sushi" sortBy:@"Meat, Seafood & Poultry"];
		[controller insertNewObject:@"Lamb" sortBy:@"Meat, Seafood & Poultry"];
		[controller insertNewObject:@"Batteries" sortBy:@"Miscellaneous"];
		[controller insertNewObject:@"Shoe Polish" sortBy:@"Miscellaneous"];
		[controller insertNewObject:@"Chilli Powder" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Curry Powder" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Garlic Powder" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Ground Ginger" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Ground Oregano" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Paprika" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Parsley" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Pepper" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Salt" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Sesame Seed" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Thyme Leaves" sortBy:@"Sauces, Spices & Seasoning"];
		[controller insertNewObject:@"Candy" sortBy:@"Snacks"];
		[controller insertNewObject:@"Popcorn" sortBy:@"Snacks"];
		[controller insertNewObject:@"Pretzels" sortBy:@"Snacks"];
		[controller insertNewObject:@"Chocolate" sortBy:@"Snacks"];
		[controller insertNewObject:@"Nuts" sortBy:@"Snacks"];
		[controller insertNewObject:@"Potato Chips" sortBy:@"Snacks"];
		[controller insertNewObject:@"Asparagus" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Avocados" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Broccoli" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Carrots" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Celery" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Cucumbers" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Garlic" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Lettuce" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Onions" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Peas" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Potatoes" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Spinach" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Squash" sortBy:@"Vegetables"];
		[controller insertNewObject:@"Tomatoes" sortBy:@"Vegetables"];
	}
}

@end
